In [2]:
import numpy as np

In [3]:
P = np.array([
[0.5, 0.6, 0.2],
[0.2, 0.3, 0.2],
[0.3, 0.1, 0.6]
])
print('Transition matrix:')
print(P)

print('The columns of P sum to', np.sum(P,axis=0))

Transition matrix:
[[0.5 0.6 0.2]
 [0.2 0.3 0.2]
 [0.3 0.1 0.6]]
The columns of P sum to [1. 1. 1.]


In [5]:
# Initial state:
x_0 = np.array([1,0,0]) # at t=0, the cat is in state 1 (sleeping)

def future_state(initial_state, time):
    # Print the probability distribution of the cat
    # after 'time', starting from 'initial_state'
    
    state = initial_state
    for i in range(time):
        state = P @ state
        
    print(f"""At time {time}, the cat is:
    -sleeping with probability {state[0]}
    - eating  with probability {state[1]}
    - playing with probability {state[2]}""")

In [6]:
future_state(x_0,1)

At time 1, the cat is:
    -sleeping with probability 0.5
    - eating  with probability 0.2
    - playing with probability 0.3


In [7]:
for i in range(10):
    future_state(x_0,i)
    print('')

At time 0, the cat is:
    -sleeping with probability 1
    - eating  with probability 0
    - playing with probability 0

At time 1, the cat is:
    -sleeping with probability 0.5
    - eating  with probability 0.2
    - playing with probability 0.3

At time 2, the cat is:
    -sleeping with probability 0.43
    - eating  with probability 0.22
    - playing with probability 0.35

At time 3, the cat is:
    -sleeping with probability 0.417
    - eating  with probability 0.22200000000000003
    - playing with probability 0.361

At time 4, the cat is:
    -sleeping with probability 0.4139
    - eating  with probability 0.2222
    - playing with probability 0.3639

At time 5, the cat is:
    -sleeping with probability 0.41305
    - eating  with probability 0.22222000000000003
    - playing with probability 0.36473

At time 6, the cat is:
    -sleeping with probability 0.412803
    - eating  with probability 0.22222200000000003
    - playing with probability 0.364975

At time 7, the cat is

In [8]:
new_initial_state = np.array([0,0.5,0.5])

for i in range(5):
    future_state(new_initial_state,i)
    print('')

At time 0, the cat is:
    -sleeping with probability 0.0
    - eating  with probability 0.5
    - playing with probability 0.5

At time 1, the cat is:
    -sleeping with probability 0.4
    - eating  with probability 0.25
    - playing with probability 0.35

At time 2, the cat is:
    -sleeping with probability 0.42
    - eating  with probability 0.22500000000000003
    - playing with probability 0.355

At time 3, the cat is:
    -sleeping with probability 0.416
    - eating  with probability 0.22250000000000003
    - playing with probability 0.36150000000000004

At time 4, the cat is:
    -sleeping with probability 0.41380000000000006
    - eating  with probability 0.22225
    - playing with probability 0.36395

